version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: .
    restart: always
    ports:
      - "80:80"
    networks:
      - appnet

volumes:
  db-data:

networks:
  appnet: